variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

stages:
  - build_plugin

build_plugin_prod:
  only:
    refs:
      - master
  stage: build_plugin
  image: 
    name: maven:3.9.8-eclipse-temurin-21-jammy
  script: "mvn clean package"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_PIPELINE_ID"
    paths: 
      - target/LeatherWorkshop*.jar
    expire_in: 90 days